using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json;

namespace TurnTelemetry.Core.Turns
{
    /// <summary>
    /// A real circuit's official turns (from a curated file in one sim), re-usable in any sim that has a SimHub map of
    /// the same circuit. Generated by tools/circuits.py into data/circuits/{id}.json.
    /// </summary>
    public sealed class CircuitTemplate
    {
        [JsonProperty("id")] public string Id;
        [JsonProperty("circuit")] public string Circuit;
        [JsonProperty("lengthMeters")] public double LengthMeters;
        [JsonProperty("reference")] public string Reference;
        [JsonProperty("turns")] public List<Turn> Turns = new List<Turn>();

        public sealed class Turn
        {
            [JsonProperty("label")] public string Label;
            [JsonProperty("name")] public string Name;
            [JsonProperty("dir")] public string Dir;
            [JsonProperty("deg")] public double Degrees;
            [JsonProperty("start")] public double Start;
            [JsonProperty("end")] public double End;
            [JsonProperty("mid")] public double Mid;

            public bool Right => string.Equals(Dir, "R", StringComparison.OrdinalIgnoreCase);
        }
    }

    public sealed class TemplateMatch
    {
        public CircuitTemplate Template;
        /// <summary>Harmonic mean of the share of template turns matched and the share of detected corners explained.</summary>
        public double Score;
        /// <summary>Template fraction f appears at (f - Offset) mod 1 in the target sim.</summary>
        public double Offset;
        public List<TurnDefinition> Turns;
    }

    /// <summary>
    /// Lines a template's turns up with corners detected on another sim's map: tries every offset that pairs a
    /// template turn with a similar detected corner, scores each, keeps the best. Port of tools/circuits.py; validated
    /// by re-creating the hand-curated ACC Silverstone and Monza files from the AC templates (scores 0.97 and 1.00, mean
    /// error 0.06-0.22% of a lap) and COTA on a second mod (1.00), while wrong circuits of the same length score at most 0.60.
    /// </summary>
    public static class CircuitTemplates
    {
        public const double LengthTolerance = 0.03;
        public const double MatchWindow = 0.012;
        public const double MinScore = 0.8;

        public static List<CircuitTemplate> LoadAll(IBundledData bundled)
        {
            var list = new List<CircuitTemplate>();
            if (bundled == null) return list;
            foreach (var path in bundled.List("data/circuits/"))
            {
                try
                {
                    var template = JsonConvert.DeserializeObject<CircuitTemplate>(bundled.Read(path));
                    if (template?.Turns?.Count > 0) list.Add(template);
                }
                catch (JsonException)
                {
                    // A broken template must not stop the others.
                }
            }
            return list;
        }

        /// <summary>Best template for this map, or null when none is close enough in length and shape.</summary>
        public static TemplateMatch Match(IEnumerable<CircuitTemplate> templates, IReadOnlyList<TrackGeometry.Corner> corners, double lengthM)
        {
            TemplateMatch best = null;
            foreach (var template in templates)
            {
                if (Math.Abs(lengthM - template.LengthMeters) > LengthTolerance * template.LengthMeters) continue;
                var (score, offset) = Align(template, corners);
                if (score >= MinScore && (best == null || score > best.Score))
                    best = new TemplateMatch { Template = template, Score = score, Offset = offset };
            }
            if (best != null) best.Turns = Place(best.Template, best.Offset);
            return best;
        }

        public static (double score, double offset) Align(CircuitTemplate template, IReadOnlyList<TrackGeometry.Corner> corners)
        {
            double bestScore = -1, bestOffset = 0;
            foreach (var t in template.Turns)
            {
                foreach (var c in corners)
                {
                    if (!Similar(t, c)) continue;
                    var offset = Cyc(t.Mid - c.Apex);
                    var score = ScoreAt(template, corners, offset, out var residuals);
                    if (score > bestScore)
                    {
                        bestScore = score;
                        bestOffset = Cyc(offset - (residuals.Count > 0 ? residuals.Average() : 0));
                    }
                }
            }
            return (Math.Max(0, bestScore), bestOffset);
        }

        /// <summary>
        /// A template turn matches a same-direction corner that contains it, or a similar corner whose apex is within
        /// MatchWindow (curated turns can be parts of one detected corner, e.g. COTA 16-18).
        /// </summary>
        private static double ScoreAt(CircuitTemplate template, IReadOnlyList<TrackGeometry.Corner> corners, double offset,
            out List<double> residuals)
        {
            residuals = new List<double>();
            var used = new HashSet<int>();
            var matched = 0;
            foreach (var u in template.Turns)
            {
                var target = Mod1(u.Mid - offset);
                double bestD = double.MaxValue;
                var bestI = -1;
                for (var i = 0; i < corners.Count; i++)
                {
                    var c = corners[i];
                    if (c.Right != u.Right) continue;
                    var d = Math.Abs(Cyc(c.Apex - target));
                    if (!(Inside(c, target) || (Similar(u, c) && d < MatchWindow))) continue;
                    if (d < bestD)
                    {
                        bestD = d;
                        bestI = i;
                    }
                }
                if (bestI < 0) continue;
                matched++;
                used.Add(bestI);
                if (Similar(u, corners[bestI]) && bestD < MatchWindow) residuals.Add(Cyc(corners[bestI].Apex - target));
            }
            if (matched == 0) return 0;
            var recall = matched / (double)template.Turns.Count;
            var precision = used.Count / (double)Math.Max(1, corners.Count);
            return 2 * recall * precision / (recall + precision);
        }

        private static bool Inside(TrackGeometry.Corner c, double target, double margin = 0.004)
        {
            var span = Mod1(c.End - c.Start);
            return Mod1(target - c.Start + margin) <= span + 2 * margin;
        }

        /// <summary>Same direction and comparable angle (within a factor of 2, ignoring kinks under 30 degrees).</summary>
        private static bool Similar(CircuitTemplate.Turn t, TrackGeometry.Corner c)
        {
            if (c.Right != t.Right) return false;
            double big = Math.Max(t.Degrees, c.Degrees), small = Math.Min(t.Degrees, c.Degrees);
            return big < 30 || big <= 2 * small;
        }

        private static List<TurnDefinition> Place(CircuitTemplate template, double offset) => template.Turns
            .Select(t => new TurnDefinition
            {
                Label = t.Label, Name = t.Name,
                Start = Math.Round(Mod1(t.Start - offset), 4), End = Math.Round(Mod1(t.End - offset), 4),
            })
            .OrderBy(t => t.Start)
            .ToList();

        private static double Cyc(double d) => Mod1(d + 0.5) - 0.5;
        private static double Mod1(double v) => ((v % 1.0) + 1.0) % 1.0;
    }
}
