<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Version>0.2.2</Version>
    <Authors>StormFuel</Authors>
    <!-- Override with: dotnet build -p:SimHubDir="D:\SimHub" -->
    <SimHubDir Condition="'$(SimHubDir)' == ''">C:\Program Files (x86)\SimHub</SimHubDir>
  </PropertyGroup>
</Project>
